from random import *
row=71

tensemarker="\nМаркер часу: "

rules=[ ["00Present Perfect","\nЗавершені дії з наголосом на результат, Present Perfect використовується для передачі важливості результату минулої дії у теперішньому часі без точного \nзазначення часу виконання дії. Дія була виконана колись у минулому (часто нещодавно), і результат цієї дії можна побачити в теперішньому часі."],
        ["01Present Perfect","\nНезакінчені дії, Present Perfect використовується для вираження дій, що почалися в не зовсім відомий момент в минулому (неважливо, коли), але ще можуть \nбути незавершеними, а результат таких дій можна побачити в теперішньому часі."],
        ["02Present Continuous","\nДії, що відбуваються зараз, Present Continuous використовується для вираження певної дії, що відбувається прямо зараз, в момент говоріння. Також Present Continuous \nвказує на одночасні дії, що відбуваються саме в цей момент."],
        ["03Present Continuous","\nДії around now, Present Continuous використовується для вираження тимчасової дії, що відбувається не в даний момент часу, а загалом в найближчий часовий проміжок – \n«around now» (приблизно в цей час)."],
        ["04Present Continuous","\nПлани на найближче майбутнє, За допомогою Present Continuous виражаються дії, що були заплановані на найближче майбутнє, особливо якщо час та місце виконання дії \nзаздалегідь відомі та сплановані."],
        ["05Present Continuous","\nОбставини, що змінюються, Present Continuous використовується для вираження ситуацій, що розвиваються або змінюються, тобто для вираження певних тенденцій."],
        ["06Present Continuous","\nНегативние ставлення до дій, Ми можемо використовувати Present Continuous для вираження свого ставлення до дій, що відбуваються постійно, або характеру певної \nлюдини, коли вони визивають в нас гнів (anger), роздратування (irritation) або вони нам докучають (annoy). Часто в таких реченнях використовуються слова \nalways (завжди), constantly (постійно, без упину), continually (безперервно)."],
        ["07Past Continuous","\nТривалі дії в певний момент або проміжок часу в минулому, Past Continuous використовується для вираження дій, що відбувалися в конкретний, точно відомий момент або \nпроміжок часу в минулому. Точний момент часу в Past Continuous може уточнюватися або перериватися іншою короткочасною дією, вираженою в Past Simple. Слова while \n(«в той час, як», «поки») та when («коли») підкреслюють та використовуються з різними частинами складнопідрядного речення. Як правило, після слова while вживається \nPast Continuous, а після when вживається Past Simple. Past Continuous використовується, якщо на питання коли це відбувалося? можна вказати точний, конкретний \nчас або проміжок часу в минулому."],
        ["08Past Continuous","\nОдночасні дії у минулому, Past Continuous використовується для вираження в одному реченні декількох дій, що відбувалися одночасно в минулому."],
        ["09Past Continuous","\nВираження несхвалення, роздратування, Past Continuous використовується для вираження несхвалення, нетерплячості або роздратованості певною дією в минулому. В \nтакому значенні Past Continuous здебільшого використовується зі словами always (завжди, постійно), often (часто), constantly (постійно). Ці слова вживаються між \nдопоміжними дієсловами was або were та смисловим дієсловом з закінченням -ing (формою дієприкметника). В такому значенні Past Continuous зхожий на конструкцію \nused to, однак відрізняється від неї своїм негативним відтінком."],
        ["10Past Continuous","\nЗаплановані дії, що не відбулися, Past Continuous використовується для вираження запланованих дій в минулому, що, однак, не відбулися. Часто в таких реченнях \nвикористовуються дієслова mean (збиратися, мати намір), intend (мати на меті, збиратися, задумати), hope (сподіватися), expect (очікувати), think (думати, гадати), \nplan (планувати)."],
        ["11Past Simple","\nНетривалі дії в неточний час у минулому, Past Simple використовується для вираження нетривалих дій, коли відомий неточний час у минулому, в який ця \nдія відбувалася. Навіть якщо мовець й не зазначив певний час, то він (цей час) все одно мається на увазі."],
        ["12Past Simple","\nДії, що завершилися в минулому, Past Simple використовується для вираження дій, що завершилися в минулому та не мають відношення (видимих результатів) у \nтеперішньому. Така дія могла буди одноразовою, повторюваною, нетривалою, або ж навпаки могла тривати певний проміжок часу, але її тривалість неважлива."],
        ["13Past Simple","\nДії, що не можуть більше повторитися, Past Simple використовується також для опису дій, що відбулися одного разу в минулому і більше не можуть повторитися \nв теперішньому або у майбутньому через певні обставини."],
        ["14Past Simple","\nПослідовні дії у минулому, Past Simple вживається для перерахування декількох дій у минулому, що відбувалися послідовно, одна за одною. Bідомий неточний час у минулому"],
        ["15Past Perfect","\nДії, що передують іншим діям в минулому або ж відбувалася до певного моменту в минулому. Past Perfect використовується для вираження дії, яка передує іншій дії у \nминулому або ж відбувалася до певного моменту в минулому."],
        ["16Past Perfect","\nВидимий результат у минулому. Past Perfect використовується для вираження дій, що завершилися в минулому й результат цих дій був також спостерігався у минулому."],
        ["17Past Perfect","\nHardly... when та No sooner...than. Past Perfect використовується в конструкціях hardly...when та no sooner...than. Ці два вирази перекладаються як «ледь я», \n«тільки-но я», «тільки щойно я». В таких реченнях Past Perfect також описує минулу дію, що відбулася перед іншою дією. Однак, особливістю є те, що в частині з \nPast Perfect використовується непрямий порядок слів (як в загальному питанні) або інверсія. В другій частині складного речення використовується час Past Simple."],
        ["18Present Simple","\nЗагальні ствердження. Present Simple використовується для вираження певного факту або інформації, що не зв'язана з певним часовим проміжком, а є актуальними \nзагалом. Часто це чиїсь звички або вподобання."],
        ["19Present Simple","\nЗагальновідомі факти. Present Simple використовується для опису загальновідомих істин, наукових фактів, явищ природи, того, що за думкою мовця завжди є незмінним."],
        ["20Present Simple","\nДії, що регулярно повторюються. Present Simple використовується для вираження дій, що регулярно відбуваються або часто повторюються. Часто це звички або \nщоденний розклад людини."],
        ["21Present Simple","\nРозклад та домовленості. Present Simple використовується для вираження розкладу чогось (потягів, автобусів, телепрограм тощо), а також певної чіткої \nдомовленості про зустріч (побачення, збори, візит до лікаря), навіть якщо мається на увазі виконання дії в майбутньому часі."],
        ["22Present Simple","\nІнструкції. Present Simple використовується в інструкціях, вказівках, рецептах тощо. В цьому випадку Present Simple має відтінок наказового способу."],
        ["23Present Simple","\nКоментарі. Present Simple використовується для зображення або опису послідовних дій, що відбуваються в цей момент, наприклад, в спортивних оглядах, \nкоментування новин, матчів, переказі історій тощо."],
        ["24Present Simple","\nЗ дієсловами що вказують не на дію, а скоріше на певний стан. Present Simple використовується з дієсловами, що вказують не на дію, а скоріше на певний \nстан, в якому перебуває особа або предмет в даний момент часу."],
        ["25Present Simple","\nВ заголовках. Present Simple використовується в заголовках газет, книг, а також в новинах та інформаційних повідомленнях для скорочення кількості \nсимволів та економії місця."],
        ["26Future Simple","\nЗагальний майбутній час. Future Simple використовується для описання поодиноких, повторюваних або послідовних дій у майбутньому."],
        ["27Future Simple","\nПрипущення на майбутнє. Future Simple використовується для вираження припущень або здогадок про майбутні дії або події. В такому випадку Future Simple \nчасто використовується в складних реченнях, де перша частина виражена дієсловом в Present Simple: think (думати, вважати), believe (вірити), expect (очікувати), \nbe afraid (боятися), be sure (бути впевненим) або ж прислівниками: probably (можливо), perhaps (мабуть), certainly (безумвно, точно) тощо."],
        ["28Future Simple","\nОбіцянки, побоювання, сподівання. Future Simple використовується для вираження обіцянок, описання чиїхось сподівань та надій щодо майбутнього. Часто цей \nчас у реченні використовується зі словами: promise (обіцяти), swear (клястися), guarantee (гарантувати), hope (сподіватися), threat (погрожувати), warn (попереджати), \nrequest (прохати, робити запит), offer (пропонувати)."],
        ["29Future Simple","\nПрогнози на майбутнє. Future Simple використовується для вираження того, що неодмінно здійсниться в майбутньому, і на що ми не можемо вплинути."],
        ["30Future Simple","\nСпонтанні рішення. Future Simple також виражає спонтанні, миттєві рішення або дії, які не були заплановані заздалегідь, а тільки-но спали на думку."],
        ["31",""]
        ]

sentences=[ ["Timothy (to feed) his dog.166/1","is feeding",rules[2][1]],
            ["Mr. Jones(to clean) his yard.166/2","is cleaning",rules[2][1]],
            ["John and his friends (to go) to the library.166/13","are going",rules[3][1]],
            ["Our neighbours (to wash) their car.166/4","are washing",rules[2][1]],
            ["I (to wash) my hair.166/5","am washing",rules[2][1]],
            ["Who (to fix) your sink?166/6","is fixing",rules[2][1]],
            ["The children (to brush) their teeth.166/8","are brushing",rules[2][1]],
            ["They (to have) a big dinner together.166/10","are having",rules[2][1]],
            ["The boys (to run) about in the garden.166/11","are running",rules[2][1]],
            ["I (to do) my homework.166/12","am doing",rules[3][1]],
            ["She is very happy: her son (to finish) school.241/1","has finished",rules[0][1]],
            ["My brother (to train) at the stadium from six till eight yesterday.241/2","was training",rules[7][1]],
            ["My sister (to buy) a pair of nice model shoes this month.241/3","has bought","\nЦей місяць ще не закінчився і моя сестра може ще купити собі взуття."+rules[1][1]],
            ["I (am/had/have) not (danced/dancing/dance) for ages.241/4","have,danced","\nЯ ще можу потанцювати століття ще не закінчилося."+rules[1][1]],
            ["When Nick (to come) from school, his friends (to play) in the yard.241/5","came,were playing",rules[7][1]],
            ["When (did/is/do) your sister (goes/go/went) to London? 241/6","did,go",rules[11][1]],
            ["My friend (is/had/has) just (recovered/recovering/recovers) after a serious illness. 241/7","has,recovered",rules[0][1]+tensemarker+"just  тільки но"],
            ["I (am/have/had) never (be/was/been) to the Bahamas.241/8","have,been","\nЯ ще можу поїхати на Багами."+rules[1][1]+tensemarker+"never ніколи."],
            ["At this time yesterday we (to talk) about you.241/9","were talking",rules[7][1]+tensemarker+"At this time yesterday."],
            ["I (to speak) to my friend yesterday.241/10","spoke",rules[11][1]+tensemarker+"yesterday."],
            ["Look! Kate (to wash) all the dishes.241/11","has washed","\nМожемо спостерігати як результат - чистий посуд."+rules[0][1]],
            ["(Have/Does/Has) your mother (returns/returned/returning) from work? Can I speak to her?241/12","has,returned","\nМама вже повернулася з роботи і запитують дозволу поговорити з нею."+rules[0][1]],
            ["She (to do) her flat the whole day on Saturday.241/13","was doing",rules[7][1]+tensemarker+"the whole day"],
            ["The cat (to drink) all the milk which I (to give) it.241/14","drank,had given","\nКіт випив молоко яке я перед тим дав йому."+rules[15][1]],
            ["(Are/Do/Have) you ever (be/been/went) to Piccadilly Circus? 241/15","have,been","\nТи ще можеш піти до цирку."+rules[1][1]+tensemarker+"ever коли небудь"],
            ["He (is reading/has not read/reads) Turgenev since he was a pupil. 241/16","has not read","\nВін ще може прочитати книжку."+rules[1][1]+tensemarker+"since."],
            ["They (to reach) the river by sunset.241/17","had reached","\nДія по досягненню до річки завершилася до певного моменту часу до заходу сонця."+rules[15][1]+tensemarker+"by sunset"],
            ["I (did not/have not/not) yet (receive/received/receiving) an answer to my letter. 241/18","have not,received","\nЯ ще можу отримати відповідь на листа."+rules[1][1]+tensemarker+"yet ще"],
            ["Only when she was going to bed, she remembered that she (to forget) to ring up her friend.241/19","had forgotten","Вона згадала це дія у минулому, забула позвонити це дія яка передує іншій дії у минулому."+rules[15][1]],
            ["We (are/have/had) already (study/studied/studies) seven English tenses.241/20","have,studied","\nМи ще можемо вивчити і більше часів."+rules[1][1]+tensemarker+"already"],
            ["He (to spend) two weeks in Scotland two years ago.241/21","spent","\nДва тижні на фоні двох років можна вважати нетривалою дією."+rules[11][1]+tensemarker+"two years ago"],
            ["I (to buy) a lovely fashionable dress. Now I shall look smart at the party.241/22","have bought",rules[0][1]],
            ["He (to learn) English before he (to go) to the USA.241/23","had learnt,went","\nВін поїхав до сполучених штатів це дія в минулому, він вивчив англійську це дія яка передує ппопередній дії в минулому."+rules[15][1]+tensemarker+"before"],
            ["When she (to spend) all her money, she (to go) home.241/24","had spent,went","\nВона пішла додому це дія в минулому, коли вона потратила всі її гроші це дія яка передує попередній дії в минулому."+rules[15][1]],
            ["Last summer we (to live) in the country and (to go) to the river every day.240/1","lived,went",rules[14][1]+tensemarker+"Last summer"],
            ["My sister (to spend) a lot of money yesterday.240/2","spent",rules[11][1]+tensemarker+"yesterday"],
            ["She is so upset: she (to lose) the key to the front door.240/3","has lost","\nБачимо результат минулої дії в теперішньому часі, вона є засмучена, вона в минулому загубила ключ."+rules[0][1]],
            ["By the 1st of September all the children (to return) from the country.240/4","had returned","\nДія відбувалася до певного моменту часу в минулому, до першого вересня."+rules[15][1]+tensemarker+"By the 1st of September"],
            ["Columbus (to discover) America 500 years ago.240/5","discovered","\nКолумб не може більше відкрити Америку."+rules[13][1]],
            ["Columbus (don't know/didn't know/ is knowing) that he (discovers/had discovered/discovered) America.240/6","didn't know,had discovered","\nКолумб в минулому зізнавався що незнав що він відкрив Америку, він думав що відкрив Індію."+rules[16][1]],
            ["I (am/had/have) already (read/reading/reading) five English books.240/7","have,read","\nЯ ще можу прочитати більше книжок."+rules[1][1]+tensemarker+"already"],
            ["He (to discuss) the problem with a lot of people before he (to take) a decision.240/8","had discussed,took","\nВін прийняв рішення це дія в минулому, він перед тим обговорив проблему з багатьма людьми це дія що передує попередній дії в минулому."+rules[15][1]+tensemarker+"before"],
            ["Mother (to bake) a delicious cake! Sit down at the table and let’s eat it! 240/9","has baked","\nОчевидно з контексту що мама спекла тістечко в минулому і воно перед нами є зараз в теперішньому часі  і нам пропонують зісти його тепер."+rules[0][1]],
            ["She (to read) an English book the whole evening yesterday. 240/10","was reading","\nВона читала увесь вечір вчора, вечір має умовний початок і умовний кінець."+rules[7][1]+tensemarker+"whole evening"],
            ["I (have/had/am) never (was/be/been) to Greece. 240/11","have,been","\nЯ ще можу поїхати до Греції."+rules[1][1]+tensemarker+"never"],
            ["They (to tell) me yesterday that you (to get) an excellent mark. 240/12","told,had got","\nВони сказали мені вчора це дія у минулому, ти отримав марку це дія що передує  іншій дії у минулому."+rules[15][1]],
            ["When (do/did/are) you (receiveed/receives/receive) a letter from your friend? 240/13","did,receive",rules[11][1]],
            ["Our grandmother (to cook) dinner from twelve till three yesterday.240/14","was cooking",rules[7][1]+tensemarker+"from twelve till three yesterday"],
            ["Look! What beautiful flowers she (to buy)! 240/15","has bought","\nКвіти можемо спостерігати зараз, квіти вона купила в минулому дія завершена в минулому"+rules[0][1]],
            ["They (to travel) along the coast of Africa last year. 240/16","travelled",rules[12][1]+tensemarker+"last year"],
            ["We (not saw/have not seen/had not seen) each other for ages.240/17","have not seen","\nМи ще можемо побачити один одного."+rules[1][1]],
            ["They (to eat) all the apples which I (to bring).240/18","ate,had brought","\nВони зїли усі яблука - це дія в минулому, які я приніс - це дія яка передувала іншій дії в минулому."+rules[15][1]],
            ["When the children (have had / had had / having) dinner, they (go/went/goes) for a walk. 240/19","had had,went",rules[16][1]],
            ["(Has/Had/Have) you ever (were/be/been) to the Niagara Falls? 240/20","Have,been","\nТи ще можеш поїхати на водоспад."+rules[1][1]+tensemarker+"ever"],
            ["At this time yesterday they (to sit) on the sofa and (to listen) to their grandmother who (to tell) them fairy tales.240/21","were sitting,listening,was telling",rules[8][1]+tensemarker+"At this time yesterday"],
            ["My friend (have/has/had) just (ring/rung/rings) me up from London. 240/22","has,rung",rules[0][1]+tensemarker+"just"],
            ["I (to stand) at the tram stop when it (to begin) raining.240/23","was standing,began",rules[7][1]],
            ["We (has not skate/have not skated/not to skate) since last winter. 240/24","have not skated","\nМи ще можемо покататися на ковзанах"+rules[1][1]+tensemarker+"since last winter"],
            ["Yesterday I (to put) five apples into the vase. Where they (to be) now? \n- I (to eat) them. You (to bring) some more tomorrow? \n- Yes, if you (not to make) noise when granny (to sleep)_247/1","put,are,have eaten,will you bring,do not make,is sleeping","\n1)"+rules[11][1]+tensemarker+"yesterday."+"\n2)Питальна форма"+rules[18][1]+"\n3)"+rules[0][1]+"\n4)"+rules[26][1]+tensemarker+"tomorrow."+"\n5) Перша частина речення"+rules[18][1]+"\nДруга частина речення  Бабуся не спить в даний момент але найближчим часом вона буде спати і тоді важливо не шуміти."+rules[3][1]],
            ["You ever (to be) to the Hermitage?_247/2","have you ever been","\nВи ще можете бути в музеї."+rules[1][1]+tensemarker+"ever"],
            ["What Nick (to do) when you (to ring) him up yesterday? - He (to play) the piano. He (to tell) that he already (to write) his composition_247/3","was Nick doing,rang,was playing,told,had already written","\n1) Перше питання"+rules[7][1]+tensemarker+" when you rang him up yesterday."+"\n2) Друге речення  аналогічно першому реченню."+rules[7][1]+"\n3)Він сказав - це дія в минулому, Він уже написав композицію - це дія яка передує попередній дії у минулому, і ця дія відбулася до певного моменту в минулому, \nще до того як він про це сказав."+rules[15][1]],
            ["Why she (to sleep) now? It (to be) too early. She never (to sleep) at this time_247/4","is she sleeping,is,sleeps","\n1)"+rules[2][1]+tensemarker+"now."+"\n2)"+rules[18][1]+"\n3)"+rules[20][1]+tensemarker+"at this time"],
            ["1)You (to go) to the library tomorrow? - 2)No, I already (to be) to the library this week. 3)I (to be) there on Monday. 4)As a rule, I (to go) to the library\nevery Wednesday. 5)But yesterday I (not to go) there, because I (not to read) the book. 6)I (to read) it now. 7)I (to go) to the library on Saturday if I \n(to finish) the book by that time._247/5","will you go,have already been,was,go,did not go,had not read,am reading,shall go,finish","\n1)"+rules[26][1]+tensemarker+"tomorrow."+"\n2)"+rules[0][1]+tensemarker+"this week."+"\n3)"+rules[11][1]+tensemarker+"on Monday."+"\n4)"+rules[20][1]+tensemarker+"every Wednesday."+"\n5)Вчора я не був у бібліотеці це дія в минулому, тому що я не прочитав книжку це дія що передує іншій дії в минулому."+rules[15][1]+"\n6)"+rules[2][1]+tensemarker+"now. Present Continuous використовується з певними словами та виразами, що вказують на певний відомий момент або проміжок часу, в який відбувається дія."+"\n7)"+rules[27][1]],
            ["As soon as I (to receive) a letter, I shall go to Lviv._247/6","receive",rules[27][1]+tensemarker+"as soon as"],
            ["By the 6 o'clock we already (to make) arrangements to take early train._247/7","had already made",rules[15][1]+tensemarker+" By the 6 o'clock"],
            ["1)Autumn (to come). 2)It (to be) November now. 3)It (to get) colder, the days (to get) shorter. 4)It often (to rain). 5)Soon it (to be) very cold._248/1","has come,is,is getting,are getting,rains,will be","\n1)Судячи з наступного речення"+rules[0][1]+"\n2)"+rules[18][1]+"\n3)"+rules[5][1]+"\n4"+rules[18][1]+"\n5)"+rules[29][1]],
            ["When I (to do) homework yesterdy, I quickly (to run) to the yard, because my friends (to wait) for me there._248/2","had done,ran,were waiting","\nWhen I (to do) homework yesterdy, I quickly (to run) to the yard"+rules[15][1]+"\nI quickly (to run) to the yard, because my friends (to wait) for me there"+rules[7][1]],
            ["We (to have) a good time last summer_248/3","had",rules[11][1]+tensemarker+"last summer"],
            ["1)What you (to learn) for today? - 2)I (to be) sorry, I (not to prepare) my lesson. 3)I (to be) ill yesterday and (not to know) what to do.\n4)I (to prepare) my lesson tomorrow. - 5)If you (not to prepare) your lesson tomorrow, you (to get) a bad mark._248/4","have you learnt,am,have not prepared,was,did not know,shall prepare,do not prepare,will get","\n1) День ще не закінчився ще можна вивчити"+rules[1][1]+"\n2)Бачимо результат в теперішньому часі, бо не вивчив і доводиться вибачатися, to be в теперішньому часі"+rules[0][1]+"\n3)"+rules[14][1]+tensemarker+"yesterday"+"\n4)"+rules[26][1]+tensemarker+"tomorrow"+"\n5)"+rules[27][1]+tensemarker+"if,tomorrow"],
            ["What you (to do) at five o'clock yesterday?_248/5","were you doing",rules[7][1]],
            ["1)Mike always (to do) his homework in the evening, 2)but today he (to begin) doing it as soon as he comes from school, 3)because his father (to promise)  \nto take him to the theatre._248/6","does,will begin,has promised","\n1)"+rules[18][1]+tensemarker+"always, in the evening"+"\n2)"+rules[26][1]+tensemarker+"as soon as"+"\n3) Результат минулої дії видно в теперішньому часі - домашнє завдання буде робитися відразу після школи, є завершена дія в минулому тато пообітцяв взяти його в театр."+rules[0][1]],
            ["71___1)When Mary (to come) home, her brother (to read) the book 2)which she (to bring) him two days before._248/7","came,was reading,had brought","\n1) Точний момент часу дії, що відбувалася в певний момент в минулому (її брат читав книжку- це тривала дія), уточнюється іншою дією в минулому (Коли Мері прийшла)"+rules[7][1]+tensemarker+"when"+"\n2)"+rules[15][1]+tensemarker+"two days before"],
            ["What you (to do) here at such a late hour? You (to write) your composition? - No, I (to write) it already. I (to work) at my report. - And when you (to write) your composition? - I (to finish) it two days ago._231/1","are you doing,are you writing,have written,am working,did you write,finished",""],
            ["I say, Tom, let's have dinner. - No, thank you, I already (to have) dinner._231/2","have already had",""],
            ["What the weather (to be) like? It still (to rain)? - No, it (to stop) raining._231/3","is the weather,is it still raining,has stopped",""],
            ["Please give me a pensil, I (to lose) mine._231/4","have lost",""],
            ["I (not to meet) Peter sinse Monday._231/5","have not met",""],
            ["Nina just (to finish) work._231/6","has just finished",""],
            ["Where Sergei (to be)? - He (to go) home. He (to leave) the room a minute ago._231/7","is,has gone,left",""],
            ["What you (to read) now? - I (to read) 'Jane Eyre' by Charlotte Bronte._231/8","are you reading,am reading",""],
            ["They (to read) 'Ivanhoe' by Walter Scott a month ago. What about you? You (to read) 'Ivanhoe'?_231/9","read,have you read","1) Past Simple-нетривала дія, коли відомий неточний час у минулому. На запитання - коли це сталося можна дати чітку але не точну відповідь. 2) Present Perfect - Незакінчена дія, навіть якщо не прочитав, то ще може прочитати"],
            ["My watch (to stop). There (to be) something wrong with it._231/10","has stopped,is",""],
            ["You (to see) Jack today? - Yes, I (to see) him at the institute._231/11","have you seen,saw",""],
            ["You (to hear) the new symphony by M.? - Yes, I....(insert here) - When you (to hear) it? - I (to hear) it last Sunday._231/12","have you heard,have,did you hear,heard",""],
            ["You (to change) so much. Anything (to happen)?._231/13","have changed,has anything happened",""],
            ["The cat (to take) a piece of fish and then (to run) away._213/1","took,ran",""],
            ["He (to read) a newspaper when I (to come) in._213/2","was reading,came",""],
            ["Yesterday I (to get) up at seven o’clock._213/3","got",""],
            ["The train (to start) at fifteen minutes to ten._213/4","started",""],
            ["He (to put) on his coat and cap, (to open) the door and (to go) out._213/5","put,opened,went",""],
            ["At this time yesterday I (to sit) at the theatre._213/6","was sitting",""],
            ["Не (to come) back to Lviv on the 15th of January._213/7","came",""],
            ["I (to go) to the institute when I (to see) him._213/8","was going,saw",""],
            ["At this time yesterday we (to have) dinner._213/9","were having",""],
            ["He (to write) a letter when I (to come) in._213/10","was writing,came",""],
            ["He (to make) a report when I (to leave) the meeting._213/11","was making,left",""],
            ["Yesterday he (to write) a letter to his friend._213/12","wrote",""],
            ["When I (to look) at them, they (to smile) at me._213/13","looked,were smiling",""],
            ["What you (to do) at six o’clock yesterday?_213/14","were you doing",""],
            ["I (to go) to bed at half past eleven._213/15","went",""],
            ["Yesterday the lesson (to begin) at nine o’clock._213/16","began",""],
            ["When somebody (to knock) at the door, she (to argue) with her husband._213/17","knocked,was arguing",""],
            ["When Pete (to jog) in the park in the morning, he (to lose) his Walkman._213/18","was jogging,lost",""],
            ["When the police (to take) the thief to the car, I (to go) to the cinema to see the new Tom Cruise film._213/19","took,was going",""],
            ["He (to shave) when he (to hear) her scream._213/20","was shaving,heard",""],
            ["Tom always (to eat) breakfast._198/1","eats",""],
            ["Yesterday he (not to eat) breakfast because he (to get) up late._198/2","did not eat,got",""],
            ["We (to like) to cook but we (not to like) to wash the dishes._198/3","like,do not like",""],
            ["He never (to shout) at his students. He (to be) a wonderful teacher, I remember._198/4","shouted,was",""],
            ["My friend (to know) Spanish very well._198/5","knows",""],
            ["Who (to ring) you up an hour ago? ._198/6","did you ring up",""],
            ["He (to live) on the third floor._198/7","lives",""],
            ["It (to take) you long to find his house yesterday?_198/8","did it take",""],
            ["When your lessons (to be) over on Monday?_198/9","when were your lessons",""],
            ["I (to have) dinner with my family yesterday._198/10","had",""],
            ["Her friends (to be) ready at five o’clock._198/11","were",""],
            ["One of her brothers (to make) a tour of Europe last summer._198/12","made",""],
            ["Queen Elizabeth II (to be) born in 1926. She (to become) Queen of England in 1952._198/13","was,became",""],
            ["You always (to get) up at seven o’clock? — No, sometimes I (to get) up at half past seven._198/14","do you always get,get",""],
            ["Antonio Stradivari (to make) wonderful violins._198/15","made",""],
            ["Who (to paint) the world-known picture 'Mona Lisa'? ._198/16","did the world-known picture 'Mona Lisa' paint",""],
            ["She (to know) all the works of Chopin. She (to enjoy) listening to his waltz last night._198/17","knows,enjoyed","1) Present Simple - Загальне ствердження, вираження певного факту або інформації що не звязана з певним проміжком часу, але є актуальна загалом, часто це чиїсь звички чи вподобання. 2) Past Simple - Нетривала дія в минулому коли відомий неточний час або Дія що завершилася в минулому, та не має відношення (видимих результатів) у теперішньому, така дія може бути одноразовою, повторюваною, нетривалою або тривати певний проміжок часу - але її тривалість неважлива. На запитання - коли це сталося можна дати чітку але не точну відповідь."],
            ["Steven’s friends (to come) to his birthday party last night and (to give) him wonderful presents. His parents (to cook) a special dinner for him. His girlfriend (to promise) to come, but she (not to be) there. He (to try) to phone, but he couldn’t get through. He (to be) really upset. Only she (not to wish) him a Happy Birthday._198/18","came,gave,cooked,promised,was not,tried,was,did not wish",""],
            ["If I (to stay) some more days in your town, I (to call) on you and we (to have) a good talk._188/1","stay,shall call,shall have",""],
            ["He (to go) to the Public Library very often when he (to be) a student._188/2","will go,is",""],
            ["As soon as I (to return) from school, I (to ring) you up._188/3","return,shall ring",""],
            ["You (to pass) many towns and villages on your way before you (to arrive) in Lviv._188/4","will pass,arrive",""],
            ["I (to stay) at home till she (to come). Then we (to go) to the theatre if she (to bring) tickets._188/5","shall stay,comes,shall go,brings",""],
            ["After I (to finish) school, I (to enter) the University._188/6","finish,shall enter",""],
            ["When he (to return) to Kiyv, he (to call) on us._188/7","returns,will call",""],
            ["If I (to see) him, I (to tell) him about their letter._188/8","see,shall tell",""],
            ["We (to gather) at our place when my brother (to come) back from Africa._188/9","shall gather,comes",""]

            ]

print("Total number of sentenses in the base is ",len(sentences),"\n")
number_of_question=0
number_of_right_answer=0
random_numbers_used=[]

while number_of_question<20:
    random_number=row
   # random_number=randint(0,len(sentences)-1)
    if not(random_number in random_numbers_used):
        random_numbers_used.append(random_number)
        number_of_question+=1
        print("Number of question:",number_of_question)
        print(sentences[random_number][0])
        answer=input()
        print("Your answer:",answer)
        print("Right answer:",sentences[random_number][1])
        print("Explanation!!!:",sentences[random_number][2])
        if answer==sentences[random_number][1]:
            print("True answer\n")
            number_of_right_answer+=1
        else:
            print("Wrong answer!!!\n")

print("You answered", int((number_of_right_answer/number_of_question)*100),"percent of the questions correctly")
input()